TESTSUITES = ./.__testsuite.sv
UNITTESTS = uvm_reg_unit_test.sv 

DEFINES += +define+UVM_NO_DPI
INCDIR += ../distrib/src
ALLPKGS += ../distrib/src/uvm_pkg.sv

include $(SVUNIT_INSTALL)/bin/cfg.mk
include $(SVUNIT_INSTALL)/bin/questa.mk
